### ISSUE TITLE
Ressource file missing

### ISSUE THREAD

**Issue by wensheng72** [Xijezu/GM-Tool#1]
Got this error : 
Erreur  1   MSB3552 : Fichier de ressources "Forms\frmGlobalUI.resx" introuvable.  Rappelz GM-Tool

Can't find frmGlobalUI.resx anywhere.

**Comment by Xijezu** [comment]
Added it, not sure why it was missing. Seems like the build-in github extension on VS Community 2015(?) is a bit buggy.
